export const fetch_rentals = "FETCH_RENTALS";
export const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID_SUCCESS";
export const FETCH_RENTAL_BY_IDINIT = "FETCH_RENTAL_BY_IDINIT";
export const FETCH_RENTAL_SUCCESS = "FETCH_RENTAL_SUCCESS";